import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
//components
import HotelAmenities from '@/components/HotelAmenities/HotelAmenities'
import Guestrooms from '@/components/Guestrooms/Guestrooms'
import Hero from '@/components/Hero'
import Decoration from '@/components/Decoration/Decoration'
import PanelSection from '@/components/PanelSection/PanelSection'
import NearbyUs from '@/components/NearbyUs'

// library Semantic UI
// import 'semantic-ui-css/semantic.min.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Cornell</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/Vectoricon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<Hero></Hero>
				<HotelAmenities />
				<Guestrooms />
				<Decoration />
				<PanelSection />
				<Decoration />
				<NearbyUs />
			</main>
		</>
	)
}
